language:
    java

sudo:
    false

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
  
after_success:
  - mvn jacoco:report coveralls:report
  
after_failure:
  - mvn jacoco:report coveralls:report

before_script:
  - git submodule update --remote --recursive

script:
  - cd sample-code-java
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B

after_script:
    sh print_surefire_reports.sh
 
